export declare class ConstantsService {
    static readonly environmentUrlsKey: string;
    static readonly disableGaKey: string;
    static readonly disableAddLoginNotificationKey: string;
    static readonly disableChangedPasswordNotificationKey: string;
    static readonly disableContextMenuItemKey: string;
    static readonly disableFaviconKey: string;
    static readonly disableAutoTotpCopyKey: string;
    static readonly enableAutoFillOnPageLoadKey: string;
    static readonly lockOptionKey: string;
    static readonly lastActiveKey: string;
    static readonly neverDomainsKey: string;
    static readonly installedVersionKey: string;
    static readonly localeKey: string;
    static readonly themeKey: string;
    static readonly collapsedGroupingsKey: string;
    static readonly autoConfirmFingerprints: string;
    static readonly dontShowCardsCurrentTab: string;
    static readonly dontShowIdentitiesCurrentTab: string;
    static readonly defaultUriMatch: string;
    static readonly pinProtectedKey: string;
    static readonly protectedPin: string;
    static readonly clearClipboardKey: string;
    readonly environmentUrlsKey: string;
    readonly disableGaKey: string;
    readonly disableAddLoginNotificationKey: string;
    readonly disableContextMenuItemKey: string;
    readonly disableFaviconKey: string;
    readonly disableAutoTotpCopyKey: string;
    readonly enableAutoFillOnPageLoadKey: string;
    readonly lockOptionKey: string;
    readonly lastActiveKey: string;
    readonly neverDomainsKey: string;
    readonly installedVersionKey: string;
    readonly localeKey: string;
    readonly themeKey: string;
    readonly collapsedGroupingsKey: string;
    readonly autoConfirmFingerprints: string;
    readonly dontShowCardsCurrentTab: string;
    readonly dontShowIdentitiesCurrentTab: string;
    readonly defaultUriMatch: string;
    readonly pinProtectedKey: string;
    readonly protectedPin: string;
    readonly clearClipboardKey: string;
}
